name: somax
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Standard Libraries
  - numpy             # Numerical Linear Algebra
  - scipy             # Scientific Computing
  - xarray            # Geoscience Data structures
  - pandas            # Unstructed Data structure
  - geopandas         # Geoscience Unstructured Data
  - scikit-learn      # Machine Learning
  - dask
  - distributed
  # CUDA Specifics
  - cuda-libraries    # cuda meta-package
  - cudnn             # specifically for cudnn
  - cuda-nvcc         # compatible nvidia C compiler is available
  # JAX
  - jaxlib
  - cuda-version      # pulling packages that are CUDA12 compatible
  - jax # ==0.4.26
  # PLOTTING LIBRARY
  - matplotlib        # standard plotting library
  - seaborn           # Stats viz library
  # Storage
  - netCDF4
  - hdf5
  - zarr
  # GUI
  - nodejs
  - jupyterlab
  - ipywidgets
  - ipykernel
  - conda-forge::tqdm
  - pip
  - pip:
      - einops
      - jaxtyping
      - equinox
      - kernex
      - FiniteDiffX
      - interpax
      - quadax
      - "git+https://github.com/adam-coogan/jaxinterp2d.git@master"
      # deep learning
      - diffrax
      # optimization
      - optax
      - jaxopt
      # OTHER
      - plum-dispatch
      # formatting
      - black
      - pylint
      - isort
      - flake8
      - mypy
      - pytest
      - pre-commit
      # Notebook stuff
      - autoroot
      - pyprojroot
      - python-dotenv
      # logging
      - wandb
      - loguru
      # plotting
      - celluloid
      - corner
      - tabulate
      # experiment
      - hydra-core
      - hydra-colorlog
      - hydra-optuna-sweeper
