"""Materialize authored simulation configs to YAML.

Imports each ``configs/_authoring/*.py`` module and writes its config
dict to ``configs/simulation/<name>.yaml``. Run from the repo root:

    python scripts/build_configs.py

This is also wired in as a DVC stage (``dvc repro build-configs``) so
that downstream simulate stages re-run automatically when any authored
config changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml


# Make the repo root importable so `import configs._authoring` works when
# this script is run via `python scripts/build_configs.py`.
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


from configs._authoring import (  # noqa: E402
    doublegyre_bc_qg,
    doublegyre_bt_qg,
    spinup_bc_qg,
    swm_jet,
)


# Single source of truth — every authored config must appear here to be
# materialized. The keys become the YAML filenames in configs/simulation/.
CONFIGS: dict[str, dict] = {
    "swm_jet": swm_jet.SwmJetConfig,
    "doublegyre_bt_qg": doublegyre_bt_qg.DoubleGyreBTQGConfig,
    "spinup_bc_qg": spinup_bc_qg.SpinupBCQGConfig,
    "doublegyre_bc_qg": doublegyre_bc_qg.DoubleGyreBCQGConfig,
}


def main() -> int:
    out_dir = REPO_ROOT / "configs" / "simulation"
    out_dir.mkdir(parents=True, exist_ok=True)

    header = (
        "# This file is generated by scripts/build_configs.py from\n"
        "# configs/_authoring/. Do NOT edit by hand — your changes will be\n"
        "# overwritten on the next `dvc repro build-configs`.\n"
    )

    for name, cfg in CONFIGS.items():
        path = out_dir / f"{name}.yaml"
        with path.open("w") as f:
            f.write(header)
            yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
